image: gitpod/workspace-full

tasks:
  - name: Install dependencies
    init: npm install @lambdatest/playwright-lambdatest
    command: npx playwright install

  - name: Run tests in parallel on LambdaTest
    command: npx playwright test --workers=4

ports:
  - port: 3000
    onOpen: open-preview
