image: gitpod/workspace-full

tasks:
  - name: Install dependencies
    init: |
      npm install
      npx playwright install
      chmod +x node_modules/.bin/playwright

  - name: Run tests
    command: npx playwright test --workers=4
