image: gitpod/workspace-full

tasks:
  - name: Install dependencies
    init: |
      npx playwright install
      npx playwright install-deps
      npm install
      chmod +x node_modules/.bin/playwright

  - name: Run tests
    command: npm run test
